---
apiVersion: v1
kind: Service
metadata:
  name: load
  labels:
    env: test
spec:
  selector:
    name: myreplica
  type: NodePort
  ports:
    - nodePort: 80
      port: 80
      targetPort: 80
      protocol: TCP