---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: test
spec:
  selector:
    type: ClusterIP
  ports:
    - targetPort: 80
      port: 8080
      protocol: TCP

  
 
          
        
