apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    env: test
spec:
  minReadySeconds: 3
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      name: mytemplate
      labels:
        app: nginx
    spec:
      containers:
        - name: mycontainer
          image: nginx:1.25
          command:
            - sleep
            - 1d
          env:
            - name: devops
              value: "bhavana"

          ports:
            - containerPort: 80
              protocol: TCP

