---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: test
spec:
  initContainers:
    - name: my-initContainers
      image: alpine
      command:
        - sleep
        - 15s
  containers:
    - name: mycontainer
      image: nginx:1.25
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
       ports:
         - containerPort: 80
           hostPort: 8080
           protocol: TCP

          
                  
        

    
    
     
    
    

      

