--- 
apiVersion: v1 
kind: Pod
metadata:
  name: bhavana-pod
  labels:
    bhavna: new
spec:

  containers:
     - name: newcontainer
       livenessProbe:
         failureThreshold: 2
       image: alpine
       args:
         - sleep
         - 10s
