---
apiVersion: v1 
kind: Pod
metadata:
  name: mypod
  labels:
    khaja: aws
spec:
  containers:
     - name: mycontainer
       image: nginx:1.25
       ports:
         - containerPort: 80
           hostPort: 8080
           protocol: TCP





  



  