---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    devops: aws
spec:
  containers:
    - name: mycontainer
      image: nginx
      ports: 
        - containerPort: 80
          hostPort: 3456
          protocol: TCP
  



 