---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  username: bhavana


---
apiVersion: v1
kind: Secret 
metadata:
  name: my-secret 
data:
  userpasswd: YmhhdmFuYQ==

---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    env: test
spec:
  containers:
    - name: mycontainer
      image: nginx:1.25
      ports:
        - containerPort: 80
          hostPort: 12345
          protocol: TCP
      envFrom:
        - configMapRef:
            name: my-configmap
        - secretRef:
            name: my-secret   
         


          
    
      

