---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  username: bhavana


---
apiVersion: v1
kind: Secret 
metadata:
  name: my-secret 
data:
  userpasswd: YmhhdmFuYQ==

---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    env: test
spec:
  containers:
    - name: mycontainer
      image: nginx:1.25
      ports:
        - containerPort: 80
          hostPort: 8080
          protocol: TCP
      volumeMounts:
        - name: ysp 
          mountPath: /var/lib/username
        - name: devops
          mountpath: /var/lib/userpasswd 
  volumes:
    - name: ysp 
      configMap:
        name: my-configmap 
    - name: devops
      secret:
        secretName:  my-secret 
 


          
    
      


